---
openapi: 3.1.0
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  title: Notification Center
  contact:
    name: Fotis Alexandrou
    url: https://www.falexandrou.com
    email: hello@falexandrou.com
  summary: Awesome Notification center
  description: |
    A notification preferences center to use as a micro-service for recording
    your user's consents. It currently features two types of consents: email_notifications
    and sms_notifications (which are self-explanatory) and provides an audit trail for the
    events that led up to the current user's consent status.
tags:
  - name: User
    description: |
      The User object is identified by a unique ID (in the form of UUID) and represents a user
      of the system. You may add a user by providing their email address and you'll get an ID
      in the response. You may then use this ID to retrieve their information and the user's
      consent status
  - name: Event
    description: |
      An event works as the audit trail to generate the user's current consent
      status. Each event should specify a consent type and whether they're enabled or not,
      plus the user it refers to. You may provide multiple events at once.
servers:
  - url: 'https://localhost:3000'
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users@{id}.yaml
  /events:
    $ref: paths/events.yaml
