---
openapi: 3.1.0
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  title: Notification Center
  summary: ''
  description: A notification preferences center to use as a micro-service
tags:
  - name: User
    description: A user object
  - name: Event
    description: An event object
servers:
  - url: 'https://localhost:3000'
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users@{id}.yaml
  /events:
    $ref: paths/events.yaml
