---
openapi: 3.1.0
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  title: Notification Center
  contact:
    name: Fotis Alexandrou
    url: https://www.falexandrou.com
    email: hello@falexandrou.com
  summary: Awesome Notification center
  description: |
    A notification preferences center to use as a micro-service for recording
    your user's consents. It currently features two types of consents: email_notifications
    and sms_notifications (which are self-explanatory) and provides an audit trail for the
    events that led up to the current user's consent status.
tags:
  - name: User
    description: A user object
  - name: Event
    description: An event object
  - name: Consent
    description: The user's consent status
servers:
  - url: 'https://localhost:3000'
paths:
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users@{id}.yaml
  /events:
    $ref: paths/events.yaml
